language: python
sudo: false
env:
  - TOX_ENV=py26-15
  - TOX_ENV=py26-16
  - TOX_ENV=py27-15
  - TOX_ENV=py27-16
  - TOX_ENV=py27-17
  - TOX_ENV=py27-18
  - TOX_ENV=py27-18-postgres
  - TOX_ENV=py27-18-mysql
  - TOX_ENV=py27-19
  - TOX_ENV=pypy-15
  - TOX_ENV=pypy-16
  - TOX_ENV=pypy-17
  - TOX_ENV=pypy-18
  - TOX_ENV=pypy-18-mysql
  - TOX_ENV=pypy-19
  - TOX_ENV=py32-16
  - TOX_ENV=py32-17
  - TOX_ENV=py32-18
  - TOX_ENV=py33-16
  - TOX_ENV=py33-17
  - TOX_ENV=py33-18
  - TOX_ENV=py34-16
  - TOX_ENV=py34-17
  - TOX_ENV=py34-18
  - TOX_ENV=py34-18-postgres
  - TOX_ENV=py34-19
before_install:
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=test_settings
  # Postgres setup.
  - # Password is 'sortedm2m'
  - psql -c "CREATE ROLE sortedm2m PASSWORD 'md5ba287bde612ca41b14776ec8f8dfdaa9' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres
  - psql -c "CREATE DATABASE sortedm2m OWNER sortedm2m;" -U postgres
  # MySQL setup.
  - echo "CREATE USER 'sortedm2m'@'localhost' IDENTIFIED BY 'sortedm2m';" | mysql -u root
  - echo "GRANT ALL PRIVILEGES ON *.* TO 'sortedm2m'@'localhost' WITH GRANT OPTION;" | mysql -u root
install:
  - pip install tox
script:
  - tox -e $TOX_ENV -v
